catatoinit: rewrite LISTEN_PID to the child process
openSUSE/catatonit pull request #15
Opened 2021-09-02 13:31 UTC by giuseppe

In order to get systemd fd passing let's rewrite the LISTEN_PID
environment variable if it is pointing to catatonit init process.

Closes: https://github.com/openSUSE/catatonit/issues/13

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

2021-09-02 13:42 UTC, alexlarsson commented
Didn't test it, but lgtm

2021-09-15 05:13 UTC, cyphar requested changes
As with the other PR, I didn't see this until now. Sorry about that.

2021-09-15 05:13 UTC, cyphar commented on catatonit.c
> +        rewrite_listen_pid_env(parent_pid);
Indentation is messed for some reason?

2021-09-15 05:13 UTC, cyphar commented on catatonit.c
> +	pid_t parent_pid = getpid();
`getppid()` is simpler and doesn't require saving a variable. So `rewrite_listen_pid_env` doesn't really need to take an argument.

2021-09-15 05:13 UTC, cyphar commented on catatonit.c
> +
While I get that on paper it's safe in this specific case, I don't like the use of `sprintf` so please use `snprintf` or `asprintf` -- but more importantly I'd prefer `strtoll` for the pid equivalence check.

2021-09-15 08:41 UTC, giuseppe commented
thanks for the review.  I've addressed your comments in the last commit

2021-09-15 10:34 UTC, cyphar approved these changes
LGTM.

2021-09-15 10:35 UTC, merged

2021-09-15 10:35 UTC, cyphar commented
I'll do a new release once #14 is merged.